steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build docker image
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    docker build \
    --tag=us-central1-docker.pkg.dev/ylebi-rnd/test-cloud-deploy/hello_world:latest \
    -f ./code/Dockerfile \
    ./code

- name: 'gcr.io/cloud-builders/docker'
  id: Push docker image with latest tag
  args: ['push', 'us-central1-docker.pkg.dev/ylebi-rnd/test-cloud-deploy/hello_world:latest']

- name: 'google/cloud-sdk:latest'
  id: Trigger Cloud Deploy
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud config set deploy/region us-central1
    gcloud deploy apply --file pipeline.yaml
    gcloud deploy apply --file target.yaml
    gcloud deploy releases create hello-world-latest-1 \
                        --delivery-pipeline=my-run-demo-app-1 \
                        --images=my-app-image=us-central1-docker.pkg.dev/ylebi-rnd/test-cloud-deploy/hello_world:latest
