apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-run-service-prod
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
spec:
  template:
    spec:
      containers:
      - image: my-app-image
